### PR TITLE
Let there be website

### PR DESCRIPTION
**Pull request by exu3**

### CODE REVIEW

**Comment by gleich** [comment]
do we wanna use ts?

**Comment by exu3** [comment]
Sure

**Comment by gleich** [comment]
@sampoder wanna review this once Ella is done?

**Comment by exu3** [comment]
Hm I'm getting this error and the page doesn't render. Any idea what's wrong here? Screen Shot 2021-12-12 at 6 07 13 PM

**Comment by sampoder** [comment]
oh I was starting something as well let me set up vercel so we get some previews

**Comment by sampoder** [comment]
I think its just a warning shouldn't break anything

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/**](https://moonbeam-site-evdde6hpz.hackclub.dev/) | [**/**](https://moonbeam-site-evdde6hpz.hackclub.dev/) |
|:-:|:-:|
|<a href="https://moonbeam-site-evdde6hpz.hackclub.dev/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/sGJYz0DkW-4gojrUxcn0mPVs_CJkO6r-Mp0Zn0nsts1rfJyBEbAiOVZjYOrHLAG96ToLduc1tmV_j5XDiF-iCQ.png">(view full size)</a> |<a href="https://moonbeam-site-evdde6hpz.hackclub.dev/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/sGJYz0DkW-4gojrUxcn0mPVs_CJkO6r-Mp0Zn0nsts1rfJyBEbAiOVZjYOrHLAG96ToLduc1tmV_j5XDiF-iCQ.png">(view full size)</a> |







Commit 4202dd99d48d692bec5dfcba32a279446c03afaa (https://moonbeam-site-evdde6hpz.hackclub.dev).

**Comment by exu3** [comment]
The console error is causing the page to not render. Likely has something to do with TypeScript types.

@sampoder thoughts on using TS vs JS?

**Comment by exu3** [comment]
Oh hmm. I think what you have on `main` is good. The content on this branch doesn't really add anything to it.

I'll close this PR.

**Pull request closed without merging**
